/**
 * Bake static level data into js/levels-data.js.
 *
 * Usage:
 *   node scripts/generate-levels.js [count]
 *   npm run generate-levels -- 150
 *
 * Default count: 100 levels (indices 0–99).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildLevelForIndex,
  levelComplexity,
  orderLevelsByComplexity,
} from "../js/level-build.js";
import { isSolvable } from "../js/logic.js";

const DEFAULT_COUNT = 100;
const rawCount = process.argv[2];
const count = rawCount == null ? DEFAULT_COUNT : Number(rawCount);

if (!Number.isFinite(count) || count < 1 || !Number.isInteger(count)) {
  console.error("Usage: node scripts/generate-levels.js [positive-integer-count]");
  process.exit(1);
}

const levels = [];
for (let i = 0; i < count; i += 1) {
  const level = buildLevelForIndex(i);
  if (!isSolvable(level.size, level.arrows)) {
    console.error(`Generated level ${i + 1} (index ${i}) is unsolvable`);
    process.exit(1);
  }
  levels.push(level);
  if ((i + 1) % 25 === 0 || i + 1 === count) {
    process.stderr.write(`Generated ${i + 1}/${count} levels\n`);
  }
}

const ordered = orderLevelsByComplexity(levels);
for (let i = 1; i < ordered.length; i += 1) {
  const prev = levelComplexity(ordered[i - 1]);
  const cur = levelComplexity(ordered[i]);
  if (cur < prev) {
    console.error(
      `Packed level ${i + 1} complexity ${cur} is below level ${i} (${prev})`,
    );
    process.exit(1);
  }
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), "../js/levels-data.js");
const header = `/** Auto-generated by scripts/generate-levels.js — do not edit by hand. */\n`;
const body = `export const LEVEL_PACK = ${JSON.stringify(ordered, null, 2)};\n`;

writeFileSync(outPath, header + body, "utf8");
console.log(`Wrote ${levels.length} levels to ${outPath}`);
