/**
 * Bake static level data into js/levels-data.js.
 *
 * Usage:
 *   node scripts/generate-levels.js [count]
 *   npm run generate-levels -- 150
 *
 * Default count: 100 levels (indices 0–99).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLevelForIndex, orderLevelsByComplexity } from "../js/level-build.js";
import { isSolvable, levelComplexity } from "../js/logic.js";

const DEFAULT_COUNT = 100;
const rawCount = process.argv[2];
const count = rawCount == null ? DEFAULT_COUNT : Number(rawCount);

if (!Number.isFinite(count) || count < 1 || !Number.isInteger(count)) {
  console.error("Usage: node scripts/generate-levels.js [positive-integer-count]");
  process.exit(1);
}

const generated = [];
for (let i = 0; i < count; i += 1) {
  const level = buildLevelForIndex(i);
  if (!isSolvable(level.size, level.arrows)) {
    console.error(`Generated level ${i + 1} (index ${i}) is unsolvable`);
    process.exit(1);
  }
  generated.push(level);
  if ((i + 1) % 25 === 0 || i + 1 === count) {
    process.stderr.write(`Generated ${i + 1}/${count} levels\n`);
  }
}

const levels = orderLevelsByComplexity(generated);
for (let i = 1; i < levels.length; i += 1) {
  const prev = levelComplexity(levels[i - 1].size, levels[i - 1].arrows);
  const next = levelComplexity(levels[i].size, levels[i].arrows);
  if (next < prev) {
    console.error(`Complexity dropped at level ${i + 1} (index ${i}): ${prev} → ${next}`);
    process.exit(1);
  }
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), "../js/levels-data.js");
const header = `/** Auto-generated by scripts/generate-levels.js — do not edit by hand. */\n`;
const body = `export const LEVEL_PACK = ${JSON.stringify(levels, null, 2)};\n`;

writeFileSync(outPath, header + body, "utf8");
console.log(`Wrote ${levels.length} levels to ${outPath}`);
